language: php

dist: trusty

git:
  depth: false

addons:
  sonarcloud:
    organization: "paul-thebaud-github"
    token: ${SONAR_TOKEN}

cache:
  directories:
    - $HOME/.composer/cache

env:
  - sonar=false

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
      env: sonar=true
    - php: nightly
  allow_failures:
    - php: nightly

before_script:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - composer self-update
  - composer global require hirak/prestissimo
  - composer update --no-interaction --no-suggest --no-progress

script:
  - phpdbg -qrr ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - if [ "$sonar" == "true" ]; then sonar-scanner; fi
